### ISSUE TITLE
クラスが少ない

### ISSUE THREAD

**Issue by kyoji63** [kyoji63/monsterzoo#2]
・Main.java，MonsterZoo.javaの二つしかない
https://github.com/kyoji63/monsterzoo/blob/95185b70b4173c84322212fa9170b229c8eecf28/src/Main.java#L3

https://github.com/kyoji63/monsterzoo/blob/95185b70b4173c84322212fa9170b229c8eecf28/src/MonsterZoo.java#L3

**Comment by kyoji63** [comment]
# 実装候補

- MonsterZooクラスをインスタンス生成のみにして，moveメソッドを別のクラスにする

https://github.com/kyoji63/monsterzoo/blob/95185b70b4173c84322212fa9170b229c8eecf28/src/MonsterZoo.java#L23-L91

- 該当箇所をGet~~.javaにまとめてモジュール化する．
- MonsterZoo.javaでimportする．
- Set~~~メソッドはSetMonsterZukan.javaに統合する．

https://github.com/kyoji63/monsterzoo/blob/95185b70b4173c84322212fa9170b229c8eecf28/src/MonsterZoo.java#L94-L116

-  SetMonsterZukanメソッドをSetMonster.javaにクラス化する．

https://github.com/kyoji63/monsterzoo/blob/1c79a07e7c2d1dab2d848401d89e2ee9fdfc5903/src/Main.java#L36-L65

**Comment by kyoji63** [comment]
・クラス間の変数はインスタンス変数を使う
https://qiita.com/gatchan03/items/e8eecf468b7dab960198#%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E5%A4%89%E6%95%B0

**Comment by Takumi1b** [comment]
・moveメソッドからmonsterクラスとeggクラスの2つに分ける
https://github.com/kyoji63/monsterzoo/blob/1c79a07e7c2d1dab2d848401d89e2ee9fdfc5903/src/MonsterZoo.java#L23-L92
